# Generated by Django 3.2.4 on 2021-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrusel_mecanicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanicos',
            name='experiencia',
            field=models.IntegerField(null=True, verbose_name='Experiencia del mecanico'),
        ),
        migrations.AlterField(
            model_name='mecanicos',
            name='edad',
            field=models.IntegerField(verbose_name='Edad del mecanico'),
        ),
    ]
