# Generated by Django 3.2.4 on 2021-07-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210713_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='descripcion',
            field=models.CharField(default=2, max_length=150, verbose_name='Descripcion del slide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrusel',
            name='titulo',
            field=models.CharField(default=2, max_length=30, verbose_name='Titulo del slide'),
            preserve_default=False,
        ),
    ]
